#!/system/bin/sh
### Disable Vsync
busybox mount -t debugfs debugfs /sys/kernel/debug
echo '0' > /sys/kernel/debug/msm_fb/0/vsync_enable
umount /sys/kernel/debug
### Optimization of all sqlite3 databases each boot
for sqlite3 in \ 
/data/data/com.android.browser/databases/webview.db
/data/data/com.android.browser/databases/autofill.db
/data/data/com.android.browser/databases/browser2.db
/data/data/com.android.providers.calendar/databases/calendar.db
/data/data/com.android.providers.contacts/databases/profile.db
/data/data/com.android.providers.contacts/databases/contacts2.db
/data/data/com.google.android.deskclock/databases/alarms.db
/data/data/com.android.providers.downloads/databases/downloads.db
/data/data/com.android.email/databases/EmailProvider.db
/data/data/com.android.email/databases/EmailProviderBody.db
/data/data/com.android.email/databases/EmailProviderBackup.db
/data/data/com.google.android.gallery3d/databases/picasa.upload.db
/data/data/com.google.android.gallery3d/databases/picasa.db
/data/data/com.google.android.gm/databases/internal.drewg29@gmail.com.db
/data/data/com.google.android.gm/databases/mailstore.drewg29@gmail.com.db
/data/data/com.google.android.gms/databases/plus.db
/data/data/com.google.android.ears/databases/heard.db
/data/data/com.google.android.partnersetup/databases/rlz_data.db
/data/data/com.google.android.gsf/databases/gservices.db
/data/data/com.google.android.gsf/databases/subscribedfeeds.db
/data/data/com.google.android.gsf/databases/googlesettings.db
/data/data/com.google.android.gsf/databases/talk.db
/data/data/com.android.keychain/databases/grants.db
/data/data/com.android.launcher/databases/launcher.db
/data/data/com.google.android.apps.maps/databases/webview.db
/data/data/com.google.android.apps.maps/databases/google_latitude_latitudeLocations.db
/data/data/com.google.android.apps.maps/databases/google_latitude_activityDetections.db
/data/data/com.google.android.apps.maps/databases/webviewCookiesChromium.db
/data/data/com.google.android.apps.maps/databases/webviewCookiesChromiumPrivate.db
/data/data/com.android.providers.media/databases/external.db
/data/data/com.android.providers.media/databases/internal.db
/data/data/com.google.android.apps.uploader/databases/picasa.upload.db
/data/data/com.google.android.apps.uploader/databases/picasa.db
/data/data/com.android.mms/databases/message_templates.db
/data/data/com.google.android.music/databases/music.db
/data/data/com.android.vending/databases/localappstate.db
/data/data/com.android.vending/databases/library.db
/data/data/com.android.vending/databases/suggestions.db
/data/data/com.android.providers.settings/databases/settings.db
/data/data/com.android.providers.telephony/databases/telephony.db
/data/data/com.android.providers.telephony/databases/mmssms.db
/data/data/com.tmobile.thememanager/databases/theme_item.db
/data/data/com.android.providers.userdictionary/databases/user_dict.db
/data/data/com.google.android.googlequicksearchbox/databases/webview.db
/data/data/com.google.android.googlequicksearchbox/databases/webviewCookiesChromium.db
/data/data/com.google.android.googlequicksearchbox/databases/webviewCookiesChromiumPrivate.db
/data/data/com.google.android.googlequicksearchbox/databases/google_analytics_v2.db
/data/data/com.google.android.googlequicksearchbox/app_webview_geolocation/CachedGeoposition.db
/data/data/com.google.android.youtube/databases/google_analytics.db
/data/data/com.google.android.youtube/databases/downloads.db
/data/data/com.jrummy.root.browser/databases/webview.db
/data/data/com.jrummy.root.browser/databases/webviewCookiesChromium.db
/data/system/users/0/accounts.db
/data/system/locksettings.db; do \ 
/system/xbin/sqlite3  'VACUUM;';
/system/xbin/sqlite3  'REINDEX;'; done;
### Ext4 File-Systems optimization & instant-mount
busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier =0,nobh /system
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /data
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /cache
### External SD I/O Tweaks
echo 8 > /sys/block/mtdblock0/bdi/read_ahead_kb
echo 8 > /sys/block/mtdblock1/bdi/read_ahead_kb
echo 8 > /sys/block/mtdblock2/bdi/read_ahead_kb
echo 8 > /sys/block/mtdblock3/bdi/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:0/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:1/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:2/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:3/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:4/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:5/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:6/read_ahead_kb
echo 128 > /sys/devices/virtual/bdi/7:7/read_ahead_kb
echo 4096 > /sys/devices/virtual/bdi/179:0/read_ahead_kb
echo 4096 > /sys/devices/virtual/bdi/default/read_ahead_kb
echo 97 > /sys/devices/virtual/bdi/179:0/max_ratio
echo 97 > /sys/devices/virtual/bdi/default/max_ratio
echo 4096 > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
### Battery Savings
echo 500 > /proc/sys/vm/dirty_expire_centisecs
echo 1000 > /proc/sys/vm/dirty_writeback_centisecs
### Block Redirects
busybox sysctl -e -w net.ipv4.conf.all.accept_redirects=0;
busybox sysctl -e -w net.ipv4.conf.default.accept_redirects=0;
busybox sysctl -e -w net.ipv4.conf.all.secure_redirects=0;
busybox sysctl -e -w net.ipv4.conf.default.secure_redirects=0;
### Block Source-Routing
busybox sysctl -e -w net.ipv4.conf.default.accept_source_route=0;
busybox sysctl -e -w net.ipv4.conf.all.accept_source_route=0;
### IPv4 Tweaks
busybox sysctl -e -w net.ipv4.tcp_timestamps=0;
busybox sysctl -e -w net.ipv4.tcp_sack=1;
busybox sysctl -e -w net.ipv4.tcp_fack=1;
busybox sysctl -e -w net.ipv4.tcp_congestion_control=cubic;
busybox sysctl -e -w net.ipv4.tcp_window_scaling=1;
### Avoid Time-Wait
busybox sysctl -e -w net.ipv4.tcp_tw_recycle=1;
busybox sysctl -e -w net.ipv4.tcp_tw_reuse=1;
### Protection against SYN Attacks
busybox sysctl -e -w net.ipv4.tcp_syncookies=1;
busybox sysctl -e -w net.ipv4.conf.all.rp_filter=1;
busybox sysctl -e -w net.ipv4.conf.default.rp_filter=1;
busybox sysctl -e -w net.ipv4.tcp_synack_retries=2;
busybox sysctl -e -w net.ipv4.tcp_syn_retries=2;
busybox sysctl -e -w net.ipv4.tcp_max_syn_backlog=1024;
busybox sysctl -e -w net.ipv4.tcp_max_tw_buckets=16384;
busybox sysctl -e -w net.ipv4.icmp_echo_ignore_all=1;
busybox sysctl -e -w net.ipv4.icmp_ignore_bogus_error_responses=1;
busybox sysctl -e -w net.ipv4.tcp_no_metrics_save=1;
busybox sysctl -e -w net.ipv4.tcp_fin_timeout=15;
busybox sysctl -e -w net.ipv4.tcp_keepalive_intvl=30;
busybox sysctl -e -w net.ipv4.tcp_keepalive_probes=5;
busybox sysctl -e -w net.ipv4.tcp_keepalive_time=1800;
busybox sysctl -e -w net.ipv4.ip_forward=0;
