PRODUCT_MAKEFILES := $(LOCAL_DIR)/d2att.mk \
$(LOCAL_DIR)/d2tmo.mk \
$(LOCAL_DIR)/d2vzw.mk \
$(LOCAL_DIR)/d2mtr.mk \
$(LOCAL_DIR)/grouper.mk \
$(LOCAL_DIR)/i605.mk \
$(LOCAL_DIR)/i9100.mk \
$(LOCAL_DIR)/i9100g.mk \
$(LOCAL_DIR)/i9300.mk \
$(LOCAL_DIR)/l900.mk \
$(LOCAL_DIR)/maguro.mk \
$(LOCAL_DIR)/mako.mk \
$(LOCAL_DIR)/n7000.mk \
$(LOCAL_DIR)/n7100.mk \
$(LOCAL_DIR)/quincyatt.mk \
$(LOCAL_DIR)/toro.mk \
$(LOCAL_DIR)/toroplus.mk \
$(LOCAL_DIR)/d2usc.mk \
$(LOCAL_DIR)/find5.mk \
$(LOCAL_DIR)/manta.mk \
$(LOCAL_DIR)/jfltecan.mk \
$(LOCAL_DIR)/tilapia.mk \
$(LOCAL_DIR)/t0lteatt.mk \
$(LOCAL_DIR)/t0ltetmo.mk \
$(LOCAL_DIR)/crespo.mk \
$(LOCAL_DIR)/passion.mk \
$(LOCAL_DIR)/wingray.mk \
$(LOCAL_DIR)/stingray.mk \
$(LOCAL_DIR)/evita.mk \
$(LOCAL_DIR)/jfltetmo.mk \
$(LOCAL_DIR)/jflteusc.mk \
$(LOCAL_DIR)/jfltevzw.mk \
$(LOCAL_DIR)/m7att.mk \
$(LOCAL_DIR)/m7spr.mk \
$(LOCAL_DIR)/m7tmo.mk \
$(LOCAL_DIR)/m7ul.mk \
$(LOCAL_DIR)/t0lte.mk
